### ISSUE TITLE
undefined method `avs_result' for nil:NilClass

### ISSUE THREAD

**Issue by ryaan-anthony** [workarea-commerce/workarea-forter#6]
Forter 1.2.3
Workarea 3.4.16

Attempting to place an order causes error:

```
NoMethodError: undefined method `avs_result' for nil:NilClass
  from workarea/forter/tender/credit_card.rb:48:in `verification_results'
  from workarea/forter/tender/credit_card.rb:23:in `to_h'
  from workarea/forter/payment.rb:38:in `build_tender_details'
  from workarea/forter/payment.rb:15:in `block in to_a'
  from workarea/forter/payment.rb:13:in `map'
  from workarea/forter/payment.rb:13:in `to_a'
  from workarea/forter/order.rb:86:in `forter_payments'
  from workarea/forter/order.rb:47:in `to_h'
  from workarea/checkout/collect_payment.decorator:8:in `purchase'
  from workarea/checkout.rb:193:in `place_order'
```

**Comment by jyucis** [comment]
@ryaan-anthony  

Can you give more details around what payment processor you are using?  It looks like the transaction has no response, which is strange because fotrter evaluates the fraud post authorization.

Is the order being placed? Can you copy and paste the response from the credit card tender? This will help troubleshoot the issue.

**Comment by jyucis** [comment]
@ryaan-anthony It seems that you are using checkout.com as a payment processor. 

Make sure to use their approved test cards here: https://docs.checkout.com/docs/testing - using anything else will result in the behavior you are describing.

**Comment by ryaan-anthony** [comment]
That's correct, checkoutdotcom plugin is installed/configured and we are using the test cards only.

**Comment by jyucis** [comment]
Can you post the response of the transaction?

**Comment by ryaan-anthony** [comment]
Sure, how can i generate a raw response?

**Comment by jyucis** [comment]
Find a failed order and get the response from the transaction: 

```
payment = Workarea::Payment.find('ORDERIDHERE')
payment.tenders.first.transactions.first.response
```

Some other helpful information:
1 - Is your payment processor in test or production mode.
2 - Is a hard error being thrown to the user or is the user going back to payment with a declined message?
